### ISSUE TITLE
tomcat 배포시 jsp가 반영되지 않는 현상

### ISSUE THREAD

**Issue by justinjeong5** [ellyheetov/diary4us#17]
# tomcat 배포시 jsp가 반영되지 않는 현상

jsp의 코드를 수정하여도 서버에 전혀 반영되지 않는다.

<a href="https://uiandwe.tistory.com/388">관련 내용의 링크</a>

**Comment by ellyheetov** [comment]
웹에서 F12를 통하여 개발자 모드 켠 후 캐쉬 비우기 및 강력 새로고침

**Comment by justinjeong5** [comment]
ㄱㅅㄱㅅ
